[package]
name = "neon-bencode"
version = "0.1.0"
authors = ["reeFridge <reefridgerator@gmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "neon_bencode"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
bip_bencode = "0.4.4"
